[package]
name = "bml-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bml-domain = { path = "../domain" }
bml-compiler = { path = "../compiler" }
crossbeam.workspace = true

[dev-dependencies]
loom.workspace = true
proptest.workspace = true
