[package]
name = "bml-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bml-domain = { path = "../domain" }
bml-compiler = { path = "../compiler" }
bml-runtime = { path = "../runtime" }
bml-parser = { path = "../parser" }
clap.workspace = true

[lib]
name = "bml_cli"
path = "src/lib.rs"
